version: '3.4'

services:
  web: &default
    build:
      context: .
    command: "rails s -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    links:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:@postgres/postgres
      - ACCESS_KEY_ID=
      - SECRET_ACCESS_KEY=
      - STORAGE_BUCKET=

  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
